[
  {
    area: "Country Lodge Community",
    geonameid: 2410001,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Freetown Road",
    geonameid: 2410002,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Lumley Mall",
    geonameid: 2410003,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Lumley Roundabout",
    geonameid: 2410004,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Lumley Beach Road",
    geonameid: 2410005,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Juba by Pass Road",
    geonameid: 2410006,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Peeka Boo Playground",
    geonameid: 2410007,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Decode Lounge",
    geonameid: 2410008,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Spur Loop Community",
    geonameid: 2410009,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Scan Drive Community",
    geonameid: 2410010,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Spur Road Community",
    geonameid: 2410011,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Middle Hill Station",
    geonameid: 2410012,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Hill Station",
    geonameid: 2410013,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Imatt",
    geonameid: 2410014,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Leicester Peak & Leicester Community",
    geonameid: 2410015,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Hill Station - South Ridge",
    geonameid: 2410016,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Hill Station - Magba Yillah",
    geonameid: 2410017,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Aberdeen Community",
    geonameid: 2410018,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Aberdeen Beach",
    geonameid: 2410019,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Murray Town",
    geonameid: 2410020,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Sir Samuel Lewis Road",
    geonameid: 2410021,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Mudge Farm",
    geonameid: 2410022,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Cole Farm",
    geonameid: 2410023,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Congo Water",
    geonameid: 2410024,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "KingTom",
    geonameid: 2410025,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "KingHarman",
    geonameid: 2410026,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Skye Street",
    geonameid: 2410027,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Old Railway Line",
    geonameid: 2410028,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "New England",
    geonameid: 2410029,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Brookfields",
    geonameid: 2410030,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Juba Hill Community",
    geonameid: 2410031,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Juba Barracks",
    geonameid: 2410032,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Levuma Beach",
    geonameid: 2410033,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Majay Town",
    geonameid: 2410034,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Femi Tunner",
    geonameid: 2410035,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Mitchem",
    geonameid: 2410036,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Goderich Milton Margai",
    geonameid: 2410037,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Goderich - Sugarloaf Beach Community",
    geonameid: 2410038,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Bango Farm",
    geonameid: 2410039,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Old Railway Line",
    geonameid: 2410040,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Siaka Steven Street",
    geonameid: 2410041,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Brook Street",
    geonameid: 2410042,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Waterloo Street",
    geonameid: 2410043,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Wellington Street",
    geonameid: 2410044,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Liverpool Street",
    geonameid: 2410045,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Gloucester Street",
    geonameid: 2410046,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Howe Street",
    geonameid: 2410047,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Rawdon Street",
    geonameid: 2410048,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Wilberforce Street",
    geonameid: 2410049,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Pademba Road",
    geonameid: 2410050,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "A.J Momoh Street (Tower Hill)",
    geonameid: 2410051,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Apex Educational Centre",
    geonameid: 2410052,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Bilkisu Investment",
    geonameid: 2410053,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Loko Batist Church",
    geonameid: 2410054,
    name: "Fully Covered",
    subarea: "Western Area",
  },
  {
    area: "Circular Road",
    geonameid: 2410055,
    name: "Fully Covered",
    subarea: "Western Area",
  },
];
